name: flutter_state_mvvm
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  smooth_page_indicator: ^1.2.0+3
  fluttertoast: ^8.2.10
  flutter_dotenv: ^5.2.1 
  permission_handler: ^11.3.1
  path: ^1.9.0
  photo_manager: ^3.6.4
  photo_manager_image_provider: ^2.2.0
  provider: ^6.1.2
  camera: ^0.11.1
  video_player: ^2.10.1
  shared_preferences: ^2.5.2    
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets: 
    - .env